# Generated by Django 3.0 on 2020-10-07 14:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('basic', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sem_name', models.CharField(blank=True, max_length=128, null=True, verbose_name='学期名')),
                ('sem_is_available', models.BooleanField(default=False, null=True, verbose_name='是否为当前学期')),
                ('sem_dep_status', models.CharField(choices=[('离校', '离校'), ('返校', '返校'), ('关闭统计', '关闭统计')], default='关闭统计', max_length=5, verbose_name='离/返校状态')),
            ],
            options={
                'verbose_name': '学期',
                'verbose_name_plural': '学期',
            },
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sco_course', models.CharField(blank=True, max_length=128, null=True, verbose_name='课程')),
                ('sco_score', models.CharField(blank=True, max_length=128, null=True, verbose_name='分数')),
                ('sco_cls', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='basic.StudentClass', verbose_name='班级')),
                ('sco_sem', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='semester.Semester', verbose_name='学期')),
                ('sco_stu', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='basic.Student', verbose_name='学生')),
            ],
            options={
                'verbose_name': '成绩',
                'verbose_name_plural': '成绩',
            },
        ),
        migrations.CreateModel(
            name='Departure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('depart_type', models.CharField(blank=True, choices=[('离校', '离校'), ('返校', '返校')], max_length=128, null=True, verbose_name='记录类型')),
                ('depart_datetime', models.DateTimeField(auto_now_add=True, verbose_name='时间')),
                ('depart_loc', models.CharField(blank=True, max_length=128, null=True, verbose_name='位置')),
                ('depart_semster', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='semester.Semester', verbose_name='学期')),
                ('depart_stu', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='basic.Student', verbose_name='学生')),
            ],
            options={
                'verbose_name': '离/返校信息',
                'verbose_name_plural': '离/返校信息',
            },
        ),
    ]
