# Generated by Django 3.0 on 2020-09-15 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='ann_pubdate',
            field=models.DateField(auto_created=True, blank=True, null=True, verbose_name='发布时间'),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='ann_file',
            field=models.ManyToManyField(blank=True, to='common.MyFile', verbose_name='关联文件'),
        ),
        migrations.AlterField(
            model_name='myfile',
            name='file_body',
            field=models.FileField(blank=True, null=True, upload_to='ann_files', verbose_name='文件'),
        ),
    ]
