# Generated by Django 3.0 on 2020-09-15 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_auto_20200915_1532'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='ann_urgency',
            field=models.CharField(choices=[('一般', '一般'), ('紧急', '紧急'), ('置顶', '置顶')], default='一般', max_length=128, verbose_name='紧急程度'),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='ann_pubdate',
            field=models.DateField(auto_now=True, null=True, verbose_name='发布时间'),
        ),
    ]
