# Generated by Django 3.0 on 2020-09-17 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_auto_20200915_1538'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='ann_urgency',
            field=models.CharField(choices=[['普通', 3], ['紧急', 2], ['置顶', 1]], default='一般', max_length=128, verbose_name='紧急程度'),
        ),
    ]
