# Generated by Django 3.0 on 2020-09-17 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_auto_20200917_1630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='ann_urgency',
            field=models.CharField(choices=[[3, '普通'], [2, '紧急'], [1, '紧急']], default='一般', max_length=128, verbose_name='紧急程度'),
        ),
    ]
