# Generated by Django 3.0 on 2020-09-17 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0005_auto_20200917_1631'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='ann_urgency',
            field=models.IntegerField(choices=[[3, '普通'], [2, '紧急'], [1, '置顶']], default='一般', max_length=128, verbose_name='紧急程度'),
        ),
    ]
