# Generated by Django 3.0 on 2020-08-19 07:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cls_name', models.CharField(blank=True, max_length=128, null=True, verbose_name='班名')),
            ],
            options={
                'verbose_name': '班级信息',
                'verbose_name_plural': '班级信息',
            },
        ),
        migrations.CreateModel(
            name='Tutor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tut_name', models.CharField(blank=True, max_length=128, null=True, verbose_name='姓名')),
                ('tut_communication', models.CharField(blank=True, max_length=128, null=True, verbose_name='导师联系方式')),
                ('tut_dorm', models.CharField(blank=True, max_length=128, null=True, verbose_name='导师楼栋号')),
                ('tut_loc', models.CharField(blank=True, max_length=128, null=True, verbose_name='家庭住址')),
                ('tut_fam', models.CharField(blank=True, max_length=128, null=True, verbose_name='家庭成员')),
                ('tut_fam_tel', models.CharField(blank=True, max_length=128, null=True, verbose_name='家庭成员联系方式')),
            ],
            options={
                'verbose_name': '导师信息',
                'verbose_name_plural': '导师信息',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stu_id', models.CharField(blank=True, max_length=128, null=True, verbose_name='学号')),
                ('stu_name', models.CharField(blank=True, max_length=128, null=True, verbose_name='姓名')),
                ('stu_college', models.CharField(blank=True, max_length=128, null=True, verbose_name='学院')),
                ('stu_major', models.CharField(blank=True, max_length=128, null=True, verbose_name='专业')),
                ('stu_gender', models.CharField(blank=True, max_length=128, null=True, verbose_name='性别')),
                ('stu_birth', models.DateField(blank=True, null=True, verbose_name='出生年月')),
                ('stu_identity', models.CharField(blank=True, max_length=128, null=True, verbose_name='身份证号')),
                ('stu_political_status', models.CharField(blank=True, choices=[('中共党员', '中共党员'), ('中共预备党员', '中共预备党员'), ('共青团员', '共青团员'), ('民革党员', '民革党员'), ('民盟党员', '民盟党员'), ('民建会员', '民建会员'), ('民进会员', '民进会员'), ('农工党党员', '农工党党员'), ('致公党党员', '致公党党员'), ('九三学社社员', '九三学社社员'), ('台盟盟员', '台盟盟员'), ('无党派人士', '无党派人士'), ('群众', '群众')], max_length=128, null=True, verbose_name='政治面貌')),
                ('stu_folk', models.CharField(blank=True, max_length=128, null=True, verbose_name='民族')),
                ('stu_tel', models.CharField(blank=True, max_length=128, null=True, verbose_name='联系方式')),
                ('stu_graduate', models.CharField(blank=True, max_length=128, null=True, verbose_name='本科毕业院校')),
                ('stu_location', models.CharField(blank=True, max_length=128, null=True, verbose_name='生源所在地')),
                ('stu_direction', models.CharField(blank=True, max_length=128, null=True, verbose_name='专业方向')),
                ('stu_class', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='basic.StudentClass', verbose_name='班级')),
                ('stu_tutor', models.ForeignKey(blank=True, max_length=128, null=True, on_delete=django.db.models.deletion.CASCADE, to='basic.Tutor', verbose_name='导师')),
            ],
            options={
                'verbose_name': '学生信息',
                'verbose_name_plural': '学生信息',
            },
        ),
        migrations.CreateModel(
            name='Poverty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('por_id', models.CharField(blank=True, max_length=128, null=True, verbose_name='学号')),
                ('por_tel', models.CharField(blank=True, max_length=128, null=True, verbose_name='联系方式')),
                ('por_family1', models.CharField(blank=True, max_length=128, null=True, verbose_name='家庭成员1')),
                ('por_family1_tel', models.CharField(blank=True, max_length=128, null=True, verbose_name='联系电话1')),
                ('por_family1_job', models.CharField(blank=True, max_length=128, null=True, verbose_name='家庭成员1工作单位')),
                ('por_family2', models.CharField(blank=True, max_length=128, null=True, verbose_name='家庭成员2')),
                ('por_family2_tel', models.CharField(blank=True, max_length=128, null=True, verbose_name='联系电话2')),
                ('por_family2_job', models.CharField(blank=True, max_length=128, null=True, verbose_name='家庭成员2工作单位')),
                ('por_is_archived', models.BooleanField(default=False, verbose_name='是否为建档立卡户')),
                ('por_info', models.TextField(blank=True, null=True, verbose_name='家庭主要情况')),
                ('por_stu', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='basic.Student', verbose_name='学生')),
            ],
            options={
                'verbose_name': '贫困生信息',
                'verbose_name_plural': '贫困生信息',
            },
        ),
        migrations.CreateModel(
            name='Employment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_id', models.CharField(blank=True, max_length=128, null=True, verbose_name='学号')),
                ('emp_gender', models.CharField(blank=True, max_length=128, null=True, verbose_name='性别')),
                ('emp_loc', models.CharField(blank=True, max_length=128, null=True, verbose_name='生源地')),
                ('emp_type', models.CharField(blank=True, max_length=128, null=True, verbose_name='师范生类别')),
                ('emp_direction', models.CharField(blank=True, max_length=128, null=True, verbose_name='毕业去向')),
                ('emp_sign_type', models.CharField(blank=True, max_length=128, null=True, verbose_name='报到证签发类别')),
                ('emp_sign_unit', models.CharField(blank=True, max_length=128, null=True, verbose_name='报到证签往单位')),
                ('emp_sign_loc', models.CharField(blank=True, max_length=128, null=True, verbose_name='签往单位所在地')),
                ('emp_file_unit', models.CharField(blank=True, max_length=128, null=True, verbose_name='档案发往单位')),
                ('emp_file_phone', models.CharField(blank=True, max_length=128, null=True, verbose_name='单位联系电话')),
                ('emp_file_loc', models.CharField(blank=True, max_length=128, null=True, verbose_name='收档单位地址')),
                ('emp_file_postcode', models.CharField(blank=True, max_length=128, null=True, verbose_name='收档单位邮政编码')),
                ('emp_info1', models.CharField(blank=True, max_length=256, null=True, verbose_name='备注')),
                ('emp_info2', models.CharField(blank=True, max_length=256, null=True, verbose_name='备注2')),
                ('emp_unit_code', models.CharField(blank=True, max_length=128, null=True, verbose_name='单位组织机构代码')),
                ('emp_unit_deal', models.CharField(blank=True, max_length=128, null=True, verbose_name='协议书')),
                ('emp_unit_name', models.CharField(blank=True, max_length=128, null=True, verbose_name='单位名称')),
                ('emp_unit_hired', models.BooleanField(default=False, verbose_name='是否聘用')),
                ('emp_unit_type', models.CharField(blank=True, max_length=128, null=True, verbose_name='单位性质')),
                ('emp_unit_industry', models.CharField(blank=True, max_length=128, null=True, verbose_name='单位行业')),
                ('emp_unit_loc', models.CharField(blank=True, max_length=128, null=True, verbose_name='单位所在地')),
                ('emp_unit_jobtype', models.CharField(blank=True, max_length=128, null=True, verbose_name='工作职位类别')),
                ('emp_unit_phone', models.CharField(blank=True, max_length=128, null=True, verbose_name='单位联系电话')),
                ('emp_unit_communicate', models.CharField(blank=True, max_length=128, null=True, verbose_name='单位联系人')),
                ('emp_stu_sendmethod', models.CharField(blank=True, max_length=128, null=True, verbose_name='派出方式')),
                ('emp_stu_phone', models.CharField(blank=True, max_length=128, null=True, verbose_name='毕业生手机号码')),
                ('emp_stu_qq', models.CharField(blank=True, max_length=128, null=True, verbose_name='毕业生QQ')),
                ('emp_stu_email', models.CharField(blank=True, max_length=128, null=True, verbose_name='毕业生电子邮箱')),
                ('emp_stu_homephone', models.CharField(blank=True, max_length=128, null=True, verbose_name='家庭联系电话')),
                ('emp_stu', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='basic.Student', verbose_name='学生')),
            ],
            options={
                'verbose_name': '就业信息',
                'verbose_name_plural': '就业信息',
            },
        ),
    ]
