# Generated by Django 3.0 on 2020-10-07 14:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('basic', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScholarshipBasic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sch_title', models.CharField(blank=True, max_length=128, null=True, verbose_name='奖学金标题')),
                ('sch_type', models.CharField(choices=[('国家奖学金', '国家奖学金'), ('省政府奖学金', '省政府奖学金'), ('学业奖学金', '学业奖学金'), ('优秀奖学金', '优秀奖学金')], max_length=128, verbose_name='奖学金类型')),
                ('sch_is_available', models.BooleanField(default=False, verbose_name='评选是否开始')),
                ('sch_pub_date', models.DateField(auto_now_add=True, verbose_name='发布时间')),
            ],
            options={
                'verbose_name': '奖学金管理',
                'verbose_name_plural': '奖学金管理',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='ScholarshipApply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_tutor_score', models.FloatField(blank=True, null=True, verbose_name='导师考核得分')),
                ('app_moral_score', models.FloatField(blank=True, null=True, verbose_name='思想品德得分')),
                ('app_course_score', models.FloatField(blank=True, null=True, verbose_name='课业成绩得分')),
                ('app_academy_score', models.FloatField(blank=True, null=True, verbose_name='学术表现得分')),
                ('app_social_score', models.FloatField(blank=True, null=True, verbose_name='社会活动得分')),
                ('app_review_results', models.CharField(choices=[('未审核', '未审核'), ('审核通过', '审核通过'), ('审核驳回', '审核驳回')], default='未审核', max_length=128, verbose_name='审核结果')),
                ('app_general_score', models.FloatField(default='0', verbose_name='综合得分')),
                ('app_sch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='scholarship.ScholarshipBasic', verbose_name='申请奖学金项目')),
                ('app_stu', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='basic.Student', verbose_name='申请人')),
            ],
            options={
                'verbose_name': '奖学金申请',
                'verbose_name_plural': '奖学金申请',
                'ordering': ['id'],
            },
        ),
    ]
