# Generated by Django 3.0 on 2020-09-14 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scholarship', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scholarshipapply',
            options={'ordering': ['id'], 'verbose_name': '奖学金申请', 'verbose_name_plural': '奖学金申请'},
        ),
        migrations.AlterModelOptions(
            name='scholarshipbasic',
            options={'ordering': ['id'], 'verbose_name': '奖学金管理', 'verbose_name_plural': '奖学金管理'},
        ),
        migrations.RemoveField(
            model_name='scholarshipapply',
            name='app_cls',
        ),
    ]
