# Generated by Django 3.0 on 2020-10-08 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholarship', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scholarshipbasic',
            name='sch_info',
            field=models.TextField(blank=True, null=True, verbose_name='备注'),
        ),
    ]
